enum SystemIcons {
  appWindow('window'),
  arrowLeft('arrow_left'),
  arrowUp('arrow_up'),
  bell('bell'),
  check('check'),
  chevronDown('chevron_down'),
  chevronLeft('chevron_left'),
  chevronRight('chevron_right'),
  chevronUp('chevron_up'),
  circleHelp('question_circle'),
  columns3('lucide-columns-3', lucide: true),
  download('download'),
  ellipsis('menu_horizontal'),
  eye('eye'),
  eyeOff('eye_no'),
  file('lucide-file-text', lucide: true),
  picture('picture'),
  film('film'),
  audio('audio_wave'),
  textDocument('lucide-file-text', lucide: true),
  code('code'),
  archive('archive'),
  folder('folder_closed'),
  folderPlus('folder_add'),
  hardDrive('harddrive'),
  house('lucide-house', lucide: true),
  layoutGrid('lucide-grid-2x2', lucide: true),
  link('link'),
  list('list'),
  loaderCircle('loader'),
  lockKeyhole('lock'),
  logOut('exit_right'),
  mail('mail'),
  messageSquare('speech_bubble'),
  palette('sun'),
  plug('link'),
  plus('plus'),
  refreshCw('refresh'),
  reply('undo'),
  send('paper_plane'),
  settings('settings'),
  share2('lucide-share-2', lucide: true),
  external('external'),
  inbox('lucide-inbox', lucide: true),
  squareActivity('heart_rate'),
  squarePen('write'),
  trash2('trash'),
  triangleAlert('warning_triangle'),
  upload('upload'),
  importFiles('lucide-import', lucide: true),
  userPlus('lucide-user-round-plus', lucide: true),
  userRound('user_male_circle'),
  users('users'),
  wifiOff('wifi_error'),
  x('cross'),
  folderOpen('folder_open');

  const SystemIcons(this.fileName, {this.lucide = false});
  final String fileName;
  final bool lucide;
  String get asset => 'assets/icons/$fileName.svg';
}
