enum SystemIcons {
  appWindow('window'),
  arrowLeft('arrow_left'),
  arrowUp('arrow_up'),
  bell('bell'),
  check('check'),
  chevronDown('chevron_down'),
  chevronLeft('chevron_left'),
  chevronRight('chevron_right'),
  chevronUp('chevron_up'),
  circleHelp('question_circle'),
  columns3('split_three'),
  download('download'),
  ellipsis('menu_horizontal'),
  eye('eye'),
  eyeOff('eye_no'),
  file('document'),
  folder('folder_closed'),
  folderPlus('folder_add'),
  hardDrive('harddrive'),
  house('home'),
  layoutGrid('grid'),
  link('link'),
  list('list'),
  loaderCircle('loader'),
  lockKeyhole('lock'),
  logOut('exit_right'),
  mail('mail'),
  messageSquare('speech_bubble'),
  palette('sun'),
  plug('link'),
  plus('plus'),
  refreshCw('refresh'),
  reply('undo'),
  send('paper_plane'),
  settings('settings'),
  share2('share'),
  external('external'),
  squareActivity('heart_rate'),
  squarePen('write'),
  trash2('trash'),
  triangleAlert('warning_triangle'),
  upload('upload'),
  importFiles('import'),
  userPlus('user_add'),
  userRound('user'),
  wifiOff('wifi_error'),
  x('cross'),
  folderOpen('folder_open');

  const SystemIcons(this.fileName);
  final String fileName;
  String get asset => 'assets/icons/$fileName.svg';
}
