name: garden_flutter
description: Garden macOS application.
publish_to: none
version: 0.1.0+1
environment:
  sdk: ^3.13.4
resolution: workspace
dependencies:
  flutter:
    sdk: flutter
  garden_client:
    path: ../client
  serverpod_flutter: ^4.0.3
  serverpod_auth_idp_flutter: ^4.0.3
  flutter_svg: ^2.3.0
  window_manager: ^0.5.2
  shared_preferences: ^2.5.5
  file_selector: ^1.1.0
  passkeys: ^2.23.1
  local_auth: ^3.0.2
  serverpod_auth_idp_client: ^4.0.3
  desktop_drop: ^0.8.0
  crypto: ^3.0.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  shared_preferences_platform_interface: ^2.4.2
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/auth-background.webp
    - assets/garden.svg
    - assets/activity.svg
    - assets/folder-closed.svg
    - assets/folder-open.svg
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans.ttf
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist-Regular.ttf
        - asset: assets/fonts/Geist-Medium.ttf
          weight: 500
    - family: GeistMono
      fonts:
        - asset: assets/fonts/GeistMono-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
